export const CHAT_LIST_INITIAL_RENDER = 14;
export const CHAT_LIST_MAX_TO_RENDER_PER_BATCH = 10;
export const CHAT_LIST_WINDOW_SIZE = 7;
export const CHAT_LIST_UPDATE_BATCH_MS = 45;

export const MESSAGE_LIST_INITIAL_RENDER = 24;
export const MESSAGE_LIST_MAX_TO_RENDER_PER_BATCH = 12;
export const MESSAGE_LIST_WINDOW_SIZE = 9;
export const MESSAGE_LIST_UPDATE_BATCH_MS = 40;

export const CONVERSATION_ACTIVITY_COALESCE_MS = 160;
export const MEDIA_SIGNED_URL_MEMORY_TTL_MS = 50 * 60 * 1000;
export const MEDIA_SIGNED_URL_CACHE_MAX_ENTRIES = 300;
