-- PulseChat Phase 26: Prototype V1 production hardening and observability.
-- Run AFTER 202608290018_phase24_rate_limit_ambiguity_fix.sql.
--
-- Privacy boundary:
--   * diagnostics contain categories, timing/status and one-way fingerprints;
--   * message/profile content, request URLs, request bodies, tokens and stacks
--     are never accepted;
--   * operational tables are unavailable to normal app clients;
--   * diagnostics and push ledgers have bounded retention.

-- ---------------------------------------------------------------------------
-- Push tickets are not delivery receipts. Preserve both lifecycle stages and
-- enough bounded polling state for the scheduled receipt worker.
-- ---------------------------------------------------------------------------

alter table public.push_delivery_log
  drop constraint if exists push_delivery_log_status_check;

update public.push_delivery_log
set status = 'ticketed'
where status = 'sent';

alter table public.push_delivery_log
  add column if not exists receipt_attempt_count integer not null default 0,
  add column if not exists last_receipt_check_at timestamptz,
  add column if not exists delivered_at timestamptz;

alter table public.push_delivery_log
  add constraint push_delivery_log_status_check
  check (status in ('claimed', 'ticketed', 'delivered', 'error')),
  add constraint push_delivery_log_receipt_attempt_check
  check (receipt_attempt_count between 0 and 20);

create index if not exists push_delivery_log_receipt_poll_idx
  on public.push_delivery_log (updated_at, id)
  where status = 'ticketed' and ticket_id is not null;

create or replace function public.claim_push_deliveries(
  target_message_id uuid,
  target_deliveries jsonb
)
returns table (
  user_id uuid,
  expo_push_token text
)
language sql
volatile
security definer
set search_path = ''
as $$
  with requested as (
    select distinct
      x.user_id,
      btrim(x.expo_push_token) as expo_push_token
    from jsonb_to_recordset(coalesce(target_deliveries, '[]'::jsonb))
      as x(user_id uuid, expo_push_token text)
    where x.user_id is not null
      and x.expo_push_token is not null
  ),
  allowed as (
    select r.user_id, r.expo_push_token
    from requested r
    join public.push_tokens pt
      on pt.user_id = r.user_id
     and pt.expo_push_token = r.expo_push_token
     and pt.enabled = true
    where exists (
      select 1
      from public.message_receipts mr
      where mr.message_id = target_message_id
        and mr.user_id = r.user_id
        and mr.read_at is null
    )
  ),
  inserted as (
    insert into public.push_delivery_log as delivery_log (
      message_id,
      user_id,
      expo_push_token,
      status
    )
    select target_message_id, a.user_id, a.expo_push_token, 'claimed'
    from allowed a
    on conflict on constraint push_delivery_log_unique_message_token
    do update set
      status = 'claimed',
      ticket_id = null,
      error_code = null,
      error_message = null,
      receipt_attempt_count = 0,
      last_receipt_check_at = null,
      delivered_at = null,
      updated_at = timezone('utc'::text, now())
    where delivery_log.status = 'error'
      and delivery_log.updated_at < timezone('utc'::text, now()) - interval '10 seconds'
    returning delivery_log.user_id, delivery_log.expo_push_token
  )
  select inserted.user_id, inserted.expo_push_token
  from inserted;
$$;

revoke all on function public.claim_push_deliveries(uuid, jsonb)
  from public, anon, authenticated;
grant execute on function public.claim_push_deliveries(uuid, jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- Authenticated, metadata-only client diagnostics.
-- ---------------------------------------------------------------------------

create table if not exists public.client_diagnostics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  operation text not null,
  platform text not null,
  app_version text not null,
  build_profile text not null,
  duration_ms integer,
  outcome text not null,
  status_code integer,
  error_fingerprint text,
  occurred_at timestamptz not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint client_diagnostics_event_check
    check (event_type in ('crash', 'startup', 'api_latency')),
  constraint client_diagnostics_operation_check
    check (operation ~ '^[a-z0-9_.-]{1,64}$'),
  constraint client_diagnostics_platform_check
    check (platform in ('android', 'ios', 'web', 'unknown')),
  constraint client_diagnostics_version_check
    check (char_length(app_version) between 1 and 32 and char_length(build_profile) between 1 and 32),
  constraint client_diagnostics_duration_check
    check (duration_ms is null or duration_ms between 0 and 120000),
  constraint client_diagnostics_outcome_check
    check (outcome in ('ok', 'error')),
  constraint client_diagnostics_status_check
    check (status_code is null or status_code between 100 and 599),
  constraint client_diagnostics_fingerprint_check
    check (error_fingerprint is null or error_fingerprint ~ '^[0-9a-f]{8,64}$')
);

create index if not exists client_diagnostics_type_time_idx
  on public.client_diagnostics (event_type, occurred_at desc);
create index if not exists client_diagnostics_operation_time_idx
  on public.client_diagnostics (operation, occurred_at desc);

alter table public.client_diagnostics enable row level security;
revoke all on table public.client_diagnostics from public, anon, authenticated;
grant select, insert, update, delete on table public.client_diagnostics to service_role;
grant usage, select on sequence public.client_diagnostics_id_seq to service_role;

create or replace function public.record_client_diagnostics(target_events jsonb)
returns integer
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  actor_user_id uuid := (select auth.uid());
  requested_count integer;
  inserted_count integer;
begin
  if actor_user_id is null then
    raise exception using errcode = '28000', message = 'Authentication required.';
  end if;
  if jsonb_typeof(target_events) is distinct from 'array' then
    raise exception using errcode = '22023', message = 'Diagnostics must be a JSON array.';
  end if;

  requested_count := jsonb_array_length(target_events);
  if requested_count not between 1 and 20 then
    raise exception using errcode = '22023', message = 'Diagnostics batch must contain 1 to 20 events.';
  end if;

  perform pulsechat_private.enforce_rate_limit(
    actor_user_id,
    'client_diagnostics_hour',
    240,
    3600
  );

  insert into public.client_diagnostics (
    user_id,
    event_type,
    operation,
    platform,
    app_version,
    build_profile,
    duration_ms,
    outcome,
    status_code,
    error_fingerprint,
    occurred_at
  )
  select
    actor_user_id,
    event.event_type,
    event.operation,
    event.platform,
    event.app_version,
    event.build_profile,
    event.duration_ms,
    event.outcome,
    event.status_code,
    event.error_fingerprint,
    event.occurred_at
  from jsonb_to_recordset(target_events) as event(
    event_type text,
    operation text,
    platform text,
    app_version text,
    build_profile text,
    duration_ms integer,
    outcome text,
    status_code integer,
    error_fingerprint text,
    occurred_at timestamptz
  )
  where event.event_type in ('crash', 'startup', 'api_latency')
    and event.operation ~ '^[a-z0-9_.-]{1,64}$'
    and event.platform in ('android', 'ios', 'web', 'unknown')
    and char_length(event.app_version) between 1 and 32
    and char_length(event.build_profile) between 1 and 32
    and (event.duration_ms is null or event.duration_ms between 0 and 120000)
    and event.outcome in ('ok', 'error')
    and (event.status_code is null or event.status_code between 100 and 599)
    and (event.error_fingerprint is null or event.error_fingerprint ~ '^[0-9a-f]{8,64}$')
    and event.occurred_at between timezone('utc'::text, now()) - interval '7 days'
      and timezone('utc'::text, now()) + interval '5 minutes';

  get diagnostics inserted_count = row_count;
  if inserted_count is distinct from requested_count then
    raise exception using errcode = '22023', message = 'One or more diagnostics are invalid.';
  end if;
  return inserted_count;
end;
$$;

revoke all on function public.record_client_diagnostics(jsonb) from public, anon;
grant execute on function public.record_client_diagnostics(jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- Server-only job state and alert ledger. These tables intentionally have no
-- authenticated RLS policies; operators inspect them through SQL/controlled
-- server tooling, never from the app.
-- ---------------------------------------------------------------------------

create table if not exists public.operational_jobs (
  job_key text primary key,
  status text not null,
  last_started_at timestamptz,
  last_succeeded_at timestamptz,
  last_failed_at timestamptz,
  processed_count integer not null default 0,
  error_code text,
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint operational_jobs_key_check check (job_key ~ '^[a-z0-9_]{1,64}$'),
  constraint operational_jobs_status_check check (status in ('running', 'ok', 'error')),
  constraint operational_jobs_count_check check (processed_count >= 0),
  constraint operational_jobs_error_check
    check (error_code is null or error_code ~ '^[A-Z0-9_]{1,64}$')
);

alter table public.operational_jobs enable row level security;
revoke all on table public.operational_jobs from public, anon, authenticated;
grant select, insert, update, delete on table public.operational_jobs to service_role;

create table if not exists public.operational_alerts (
  alert_key text primary key,
  severity text not null,
  active boolean not null,
  observed_value numeric not null,
  threshold_value numeric not null,
  detail_code text not null,
  first_triggered_at timestamptz,
  last_evaluated_at timestamptz not null,
  resolved_at timestamptz,
  constraint operational_alerts_key_check check (alert_key ~ '^[a-z0-9_]{1,64}$'),
  constraint operational_alerts_severity_check check (severity in ('warning', 'critical')),
  constraint operational_alerts_detail_check check (detail_code ~ '^[A-Z0-9_]{1,64}$')
);

alter table public.operational_alerts enable row level security;
revoke all on table public.operational_alerts from public, anon, authenticated;
grant select, insert, update, delete on table public.operational_alerts to service_role;

create or replace function pulsechat_private.set_operational_alert(
  target_alert_key text,
  target_severity text,
  target_active boolean,
  target_observed_value numeric,
  target_threshold_value numeric,
  target_detail_code text
)
returns void
language sql
volatile
security definer
set search_path = ''
as $$
  insert into public.operational_alerts as alert_row (
    alert_key,
    severity,
    active,
    observed_value,
    threshold_value,
    detail_code,
    first_triggered_at,
    last_evaluated_at,
    resolved_at
  ) values (
    target_alert_key,
    target_severity,
    target_active,
    target_observed_value,
    target_threshold_value,
    target_detail_code,
    case when target_active then timezone('utc'::text, now()) end,
    timezone('utc'::text, now()),
    case when target_active then null else timezone('utc'::text, now()) end
  )
  on conflict (alert_key) do update set
    severity = excluded.severity,
    active = excluded.active,
    observed_value = excluded.observed_value,
    threshold_value = excluded.threshold_value,
    detail_code = excluded.detail_code,
    first_triggered_at = case
      when excluded.active and not alert_row.active then timezone('utc'::text, now())
      when excluded.active then alert_row.first_triggered_at
      else null
    end,
    last_evaluated_at = timezone('utc'::text, now()),
    resolved_at = case
      when excluded.active then null
      when alert_row.active then timezone('utc'::text, now())
      else alert_row.resolved_at
    end;
$$;

revoke all on function pulsechat_private.set_operational_alert(text, text, boolean, numeric, numeric, text)
  from public, anon, authenticated;

create or replace function public.evaluate_operational_alerts()
returns table (
  alert_key text,
  severity text,
  observed_value numeric,
  threshold_value numeric,
  detail_code text
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  metric_value numeric;
  sample_count numeric;
begin
  select count(*)::numeric into metric_value
  from public.client_diagnostics diagnostic
  where diagnostic.event_type = 'crash'
    and diagnostic.occurred_at >= timezone('utc'::text, now()) - interval '15 minutes';
  perform pulsechat_private.set_operational_alert(
    'client_crash_burst', 'critical', metric_value >= 3, metric_value, 3, 'CRASHES_15M'
  );

  select
    count(*)::numeric,
    coalesce(100.0 * count(*) filter (where diagnostic.outcome = 'error') / nullif(count(*), 0), 0)
    into sample_count, metric_value
  from public.client_diagnostics diagnostic
  where diagnostic.event_type = 'api_latency'
    and diagnostic.occurred_at >= timezone('utc'::text, now()) - interval '15 minutes';
  perform pulsechat_private.set_operational_alert(
    'api_error_ratio', 'critical', sample_count >= 20 and metric_value >= 10,
    metric_value, 10, 'API_ERROR_PERCENT_15M'
  );

  select coalesce(percentile_disc(0.95) within group (order by diagnostic.duration_ms), 0)::numeric
    into metric_value
  from public.client_diagnostics diagnostic
  where diagnostic.event_type = 'startup'
    and diagnostic.duration_ms is not null
    and diagnostic.occurred_at >= timezone('utc'::text, now()) - interval '24 hours';
  perform pulsechat_private.set_operational_alert(
    'slow_startup_p95', 'warning', metric_value >= 5000,
    metric_value, 5000, 'STARTUP_P95_MS_24H'
  );

  select
    count(*)::numeric,
    coalesce(100.0 * count(*) filter (where delivery.status = 'error') / nullif(count(*), 0), 0)
    into sample_count, metric_value
  from public.push_delivery_log delivery
  where delivery.created_at >= timezone('utc'::text, now()) - interval '30 minutes'
    and delivery.status in ('ticketed', 'delivered', 'error');
  perform pulsechat_private.set_operational_alert(
    'push_error_ratio', 'critical', sample_count >= 10 and metric_value >= 15,
    metric_value, 15, 'PUSH_ERROR_PERCENT_30M'
  );

  select count(*)::numeric into metric_value
  from public.push_delivery_log delivery
  where delivery.status = 'ticketed'
    and delivery.updated_at < timezone('utc'::text, now()) - interval '30 minutes';
  perform pulsechat_private.set_operational_alert(
    'stale_push_receipts', 'warning', metric_value >= 10,
    metric_value, 10, 'STALE_TICKETS_30M'
  );

  select coalesce(
    extract(epoch from (timezone('utc'::text, now()) - job.last_succeeded_at)) / 60,
    9999
  )::numeric into metric_value
  from (select 1) seed
  left join public.operational_jobs job on job.job_key = 'push_receipt_poll';
  perform pulsechat_private.set_operational_alert(
    'receipt_poller_stale', 'critical', metric_value >= 15,
    metric_value, 15, 'RECEIPT_POLLER_STALE_MINUTES'
  );

  select coalesce(sum(
    case when coalesce(object_row.metadata ->> 'size', '') ~ '^[0-9]+$'
      then (object_row.metadata ->> 'size')::numeric else 0 end
  ), 0) into metric_value
  from storage.objects object_row
  where object_row.bucket_id in ('avatars', 'chat-media');
  perform pulsechat_private.set_operational_alert(
    'storage_budget', 'warning', metric_value >= 536870912,
    metric_value, 536870912, 'STORAGE_BYTES_TOTAL'
  );

  return query
  select alert_row.alert_key, alert_row.severity, alert_row.observed_value,
    alert_row.threshold_value, alert_row.detail_code
  from public.operational_alerts alert_row
  where alert_row.active
  order by case alert_row.severity when 'critical' then 0 else 1 end,
    alert_row.alert_key;
end;
$$;

revoke all on function public.evaluate_operational_alerts() from public, anon, authenticated;
grant execute on function public.evaluate_operational_alerts() to service_role;

-- SQL-editor dashboards remain in the private schema and expose aggregates,
-- not message/profile content.
create or replace view pulsechat_private.rate_limit_dashboard
with (security_invoker = true)
as
select
  state_row.action_key,
  count(*) as actor_count,
  max(state_row.event_count) as max_event_count,
  max(state_row.updated_at) as last_activity_at
from pulsechat_private.rate_limit_state state_row
where state_row.updated_at >= timezone('utc'::text, now()) - interval '24 hours'
group by state_row.action_key;

create or replace view pulsechat_private.storage_dashboard
with (security_invoker = true)
as
select
  object_row.bucket_id,
  count(*) as object_count,
  coalesce(sum(
    case when coalesce(object_row.metadata ->> 'size', '') ~ '^[0-9]+$'
      then (object_row.metadata ->> 'size')::bigint else 0 end
  ), 0) as total_bytes,
  max(object_row.created_at) as newest_object_at
from storage.objects object_row
where object_row.bucket_id in ('avatars', 'chat-media')
group by object_row.bucket_id;

revoke all on pulsechat_private.rate_limit_dashboard from public, anon, authenticated;
revoke all on pulsechat_private.storage_dashboard from public, anon, authenticated;

create or replace function public.run_operational_maintenance()
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  deleted_diagnostics integer := 0;
  deleted_push_logs integer := 0;
  active_alert_count integer := 0;
begin
  delete from public.client_diagnostics diagnostic
  where diagnostic.created_at < timezone('utc'::text, now()) - interval '30 days';
  get diagnostics deleted_diagnostics = row_count;

  delete from public.push_delivery_log delivery
  where delivery.created_at < timezone('utc'::text, now()) - interval '30 days';
  get diagnostics deleted_push_logs = row_count;

  delete from pulsechat_private.rate_limit_state state_row
  where state_row.updated_at < timezone('utc'::text, now()) - interval '2 days';

  delete from public.operational_alerts alert_row
  where not alert_row.active
    and alert_row.resolved_at < timezone('utc'::text, now()) - interval '90 days';

  select count(*) into active_alert_count
  from public.evaluate_operational_alerts();

  insert into public.operational_jobs as job_row (
    job_key, status, last_started_at, last_succeeded_at, processed_count, error_code, updated_at
  ) values (
    'operational_maintenance', 'ok', timezone('utc'::text, now()),
    timezone('utc'::text, now()), deleted_diagnostics + deleted_push_logs, null,
    timezone('utc'::text, now())
  )
  on conflict (job_key) do update set
    status = 'ok',
    last_started_at = excluded.last_started_at,
    last_succeeded_at = excluded.last_succeeded_at,
    processed_count = excluded.processed_count,
    error_code = null,
    updated_at = excluded.updated_at;

  return jsonb_build_object(
    'deletedDiagnostics', deleted_diagnostics,
    'deletedPushLogs', deleted_push_logs,
    'activeAlerts', active_alert_count
  );
end;
$$;

revoke all on function public.run_operational_maintenance() from public, anon, authenticated;
grant execute on function public.run_operational_maintenance() to service_role;

comment on table public.client_diagnostics is
  'Phase 26: private, metadata-only client crash/startup/API diagnostics with 30-day retention.';
comment on table public.operational_jobs is
  'Phase 26: server-only scheduled-job freshness and outcome ledger.';
comment on table public.operational_alerts is
  'Phase 26: server-only evaluated alert state without user content.';
